person:
  name: wdj
  age: 10

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #      static-path-pattern: /res/**
  resources:
    static-locations:  [classpath:/static_html/,classpath:/static/]
