person:
  name: wdj
  age: 10

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    # static-path-pattern: /res/**
    contentnegotiation:
      favor-parameter: true

  resources:
    static-locations: [ classpath:/static_html/,classpath:/static/ ]

  datasource:
#    url: jdbc:mysql://192.168.0.44:3306/dbCloud?useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: jdbc:mysql://192.168.56.128:3306/dbCloud?useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.56.128
    password: 123456

mybatis:
  #  如果需要以xml的方式配置mybatis，可以指定文件，通常在properties里配置，不在xml里配置
  #  config-location: classpath:mybatis/mybatis-config.xml
  # 指定mapper文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: sj.springboot.learn.mybatis
  configuration:
    #开启驼峰规则。数据库中通常user_id，对应java中userId，如果不开启那么无法将user_id绑定到userId中
    map-underscore-to-camel-case: true